version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-pos
    ports:
      - 9090:9090
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./config/.env.yml:/app/config/.env.yml

  mysql:
    image: mysql:5.7 
    container_name: mini-pos
    command: mysqld --user=root
    volumes:
      - ./mini-pos.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mini_pos
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
